baseURL = "https://shrub.space/"
languageCode = "en-gb"
pluralizelisttitles = "false"
theme = "shrub"
title = "Shrub Co-op"
[[menu.main]]
identifier = "blog"
name = "Blog"
pre = "This is the link to the Blog section of the site. Click here to read our latest blog posts"
url = "/blog/"
weight = 5
[[menu.main]]
identifier = "events"
name = "Events"
pre = "This is the link to the Events section of the site. Click here to read about our latest events"
url = "/events/"
weight = 4
[[menu.main]]
identifier = "contact"
name = "Contact"
pre = "This is the Contact section of the site. Click here to find out how to send us an email."
url = "/contact/"
weight = 2
[[menu.main]]
identifier = "get-involved"
name = "Get Involved"
pre = "This is the link to the Get Involved section of the site. Click here to Volunteer with us, Sign up to our Newsletter or become a Member of Shrub."
url = "/get-involved/"
weight = 3
[[menu.main]]
identifier = "about-us"
name = "About Us"
pre = "Click this link to find out about us and why we exist."
url = "/about-us/"
weight = 1
[params]
murakamiKey = "UUGLwdSBrFutmfmBnA8ccC4BC5DEVbVk"
[taxonomies]
category = "categories"
tag = "tags"
